### ISSUE TITLE
Build on other platforms

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-asl#8]
I like to be able to configure log levels and log destinations on the command-line: it useful to use stderr for debugging and then the system log (ASL or the Windows event log or syslog) in production. I don't enjoy writing programs which pre-process the source to omit logging systems like `asl` which will break the build on other platforms. Perhaps we could make this code build on other platforms and make it a runtime error to try to use it? IIRC this is the pattern that `conduit` already uses (although it does use pre-processing internally this is hidden from users)

**Comment by talex5** [comment]
What about this [handy tool](https://github.com/mirage/mirage/) for selecting the correct modules to use given a target platform and desired configuration?

**Comment by djs55** [comment]
It would be great if we could have first-class support for OSX and Windows applications in `mirage` so that we could use the event log or the apple system log, named pipes or Unix domain sockets or `AF_HYPERV`, `launchd` or whatever Windows does for services. Definitely a good target to aim for!
